services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: swshop
      POSTGRES_PASSWORD: swshop
      POSTGRES_DB: sw-shop
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./views.sql:/docker-entrypoint-initdb.d/views.sql
    ports:
      - 2345:5432
volumes:
  pgdata: